### ISSUE TITLE
Many xCode warnings when building

### ISSUE THREAD

**Issue by Joebayld** [eonist/swift-utils#7]
Hi, 

I've noticed when trying to build this product that I'm thrown many issues. Most of them are from multiple objects conforming to the same protocol. There's also some other things that need to be addressed. Is this expected? Shall I create a PR? See attached screenshot. 
<img width="693" alt="issues" src="https://user-images.githubusercontent.com/9399317/29245146-7af76f3a-7f9e-11e7-9295-d75a90d23d2b.png">

**Comment by eonist** [comment]
@Joebayld I will have a look.

**Comment by eonist** [comment]
@Joebayld Alright bumped the tag releases to use the latest code. Let me know if it's working. Are you using SPM or?

**Comment by Joebayld** [comment]
I'm using SPM. Got the new tag, it has fixes, but still a few things wrong. They are simple fixes though. 
<img width="855" alt="issues" src="https://user-images.githubusercontent.com/9399317/29260305-0029ac10-8097-11e7-85a5-3277192d7f91.png">



_**if you use the following code, it will resolve the first error.**_ 
```
  private let eventCallback:FSEventStreamCallback = {(
      stream:ConstFSEventStreamRef, contextInfo:UnsafeMutableRawPointer?, numEvents:Int,
      eventPaths:UnsafeMutableRawPointer, eventFlags:UnsafePointer<FSEventStreamEventFlags>,
      eventIds:UnsafePointer<FSEventStreamEventId>
    ) in
    let fileSystemWatcher = Unmanaged<FileWatcher>.fromOpaque(contextInfo!).takeUnretainedValue()
    let paths = Unmanaged<CFArray>.fromOpaque(eventPaths).takeUnretainedValue() as! [String]
    
    for index in 0..<numEvents {
      fileSystemWatcher.callback?(FileWatcherEvent(eventIds[index], paths[index], eventFlags[index]))
    }
  }
```

On another note - is this meant to be built as a framework and used? Or should all the files live in my app project? When I run 'swift package generate-xcodeproj', it creates a Xcode framework project will all the code attached. this is fine, however, nothing in Swift Utils is exposed public, so I can't really use the code. Would love to know how this should properly be used.

**Comment by eonist** [comment]
What Xcode are You running? 8.3.3 ? Ci travis doesn't display any warnings as of yesterday. I'm migrating to Xcode 9 pretty soon probably. And Nothing is Exposed, I use @testable import Utils instead. In the future I will break the library up into smaller pieces with proper exposure. Right now it's more academic and a way to organize my code. I made a tutorial series about how I use frameoworks that you can check out: http://eon.codes/blog/2017/02/25/The-ultimate-XCode-workflow/

**Comment by Joebayld** [comment]
Ah! I'm running it on Xcode 9. That likely explains it. Yeah it just looks like some API changes in 9. 

Totally get it on the @testable. All good.

**Comment by eonist** [comment]
Moved to XCode 9 and swift 4. New release soon. Need to check if CI Travis is xcode 9 + swift ready
